// ============================================================================
// platform/linux/wayland/keycode.rs — Linux 键码 → KeyCode 转换
// ============================================================================

use crate::platform::windowing::KeyCode;

/// 将 Linux evdev 键码映射到平台无关的 KeyCode。
pub(crate) fn linux_keycode_to_keycode(code: u32) -> KeyCode {
    match code {
        1 => KeyCode::Escape,
        2..=11 => [
            KeyCode::Num1,
            KeyCode::Num2,
            KeyCode::Num3,
            KeyCode::Num4,
            KeyCode::Num5,
            KeyCode::Num6,
            KeyCode::Num7,
            KeyCode::Num8,
            KeyCode::Num9,
            KeyCode::Num0,
        ][(code - 2) as usize],
        12 => KeyCode::Minus,
        13 => KeyCode::Equal,
        26 => KeyCode::LeftBracket,
        27 => KeyCode::RightBracket,
        39 => KeyCode::Semicolon,
        40 => KeyCode::Quote,
        41 => KeyCode::Backquote,
        43 => KeyCode::Backslash,
        51 => KeyCode::Comma,
        52 => KeyCode::Period,
        53 => KeyCode::Slash,
        14 => KeyCode::Backspace,
        15 => KeyCode::Tab,
        16 => KeyCode::Q,
        17 => KeyCode::W,
        18 => KeyCode::E,
        19 => KeyCode::R,
        20 => KeyCode::T,
        21 => KeyCode::Y,
        22 => KeyCode::U,
        23 => KeyCode::I,
        24 => KeyCode::O,
        25 => KeyCode::P,
        28 => KeyCode::Enter,
        29 => KeyCode::Ctrl,
        30 => KeyCode::A,
        31 => KeyCode::S,
        32 => KeyCode::D,
        33 => KeyCode::F,
        34 => KeyCode::G,
        35 => KeyCode::H,
        36 => KeyCode::J,
        37 => KeyCode::K,
        38 => KeyCode::L,
        42 => KeyCode::Shift,
        44 => KeyCode::Z,
        45 => KeyCode::X,
        46 => KeyCode::C,
        47 => KeyCode::V,
        48 => KeyCode::B,
        49 => KeyCode::N,
        50 => KeyCode::M,
        56 => KeyCode::Alt,
        57 => KeyCode::Space,
        59..=68 => [
            KeyCode::F1,
            KeyCode::F2,
            KeyCode::F3,
            KeyCode::F4,
            KeyCode::F5,
            KeyCode::F6,
            KeyCode::F7,
            KeyCode::F8,
            KeyCode::F9,
            KeyCode::F10,
        ][(code - 59) as usize],
        87 => KeyCode::F11,
        88 => KeyCode::F12,
        97 => KeyCode::Ctrl,
        100 => KeyCode::Alt,
        102 => KeyCode::Home,
        103 => KeyCode::Up,
        104 => KeyCode::PageUp,
        105 => KeyCode::Left,
        106 => KeyCode::Right,
        107 => KeyCode::End,
        108 => KeyCode::Down,
        109 => KeyCode::PageDown,
        110 => KeyCode::Insert,
        111 => KeyCode::Delete,
        71 => KeyCode::Num7,
        72 => KeyCode::Num8,
        73 => KeyCode::Num9,
        75 => KeyCode::Num4,
        76 => KeyCode::Num5,
        77 => KeyCode::Num6,
        79 => KeyCode::Num1,
        80 => KeyCode::Num2,
        81 => KeyCode::Num3,
        82 => KeyCode::Num0,
        125 | 126 => KeyCode::Super,
        _ => KeyCode::Unknown,
    }
}

/// 将 KeyCode 转换为可打印字符（仅处理 ASCII 可打印范围）。
pub(crate) fn keycode_to_char(code: KeyCode, shift: bool) -> Option<String> {
    use KeyCode::*;
    let ch = match (code, shift) {
        (A, false) => 'a',
        (A, true) => 'A',
        (B, false) => 'b',
        (B, true) => 'B',
        (C, false) => 'c',
        (C, true) => 'C',
        (D, false) => 'd',
        (D, true) => 'D',
        (E, false) => 'e',
        (E, true) => 'E',
        (F, false) => 'f',
        (F, true) => 'F',
        (G, false) => 'g',
        (G, true) => 'G',
        (H, false) => 'h',
        (H, true) => 'H',
        (I, false) => 'i',
        (I, true) => 'I',
        (J, false) => 'j',
        (J, true) => 'J',
        (K, false) => 'k',
        (K, true) => 'K',
        (L, false) => 'l',
        (L, true) => 'L',
        (M, false) => 'm',
        (M, true) => 'M',
        (N, false) => 'n',
        (N, true) => 'N',
        (O, false) => 'o',
        (O, true) => 'O',
        (P, false) => 'p',
        (P, true) => 'P',
        (Q, false) => 'q',
        (Q, true) => 'Q',
        (R, false) => 'r',
        (R, true) => 'R',
        (S, false) => 's',
        (S, true) => 'S',
        (T, false) => 't',
        (T, true) => 'T',
        (U, false) => 'u',
        (U, true) => 'U',
        (V, false) => 'v',
        (V, true) => 'V',
        (W, false) => 'w',
        (W, true) => 'W',
        (X, false) => 'x',
        (X, true) => 'X',
        (Y, false) => 'y',
        (Y, true) => 'Y',
        (Z, false) => 'z',
        (Z, true) => 'Z',
        (Num1, false) => '1',
        (Num1, true) => '!',
        (Num2, false) => '2',
        (Num2, true) => '@',
        (Num3, false) => '3',
        (Num3, true) => '#',
        (Num4, false) => '4',
        (Num4, true) => '$',
        (Num5, false) => '5',
        (Num5, true) => '%',
        (Num6, false) => '6',
        (Num6, true) => '^',
        (Num7, false) => '7',
        (Num7, true) => '&',
        (Num8, false) => '8',
        (Num8, true) => '*',
        (Num9, false) => '9',
        (Num9, true) => '(',
        (Num0, false) => '0',
        (Num0, true) => ')',
        (Space, _) => ' ',
        // 标点按 US 布局直接映射；非 US 布局由输入法路径补充。
        (Minus, false) => '-',
        (Minus, true) => '_',
        (Equal, false) => '=',
        (Equal, true) => '+',
        (LeftBracket, false) => '[',
        (LeftBracket, true) => '{',
        (RightBracket, false) => ']',
        (RightBracket, true) => '}',
        (Semicolon, false) => ';',
        (Semicolon, true) => ':',
        (Quote, false) => '\'',
        (Quote, true) => '"',
        (Backquote, false) => '`',
        (Backquote, true) => '~',
        (Backslash, false) => '\\',
        (Backslash, true) => '|',
        (Comma, false) => ',',
        (Comma, true) => '<',
        (Period, false) => '.',
        (Period, true) => '>',
        (Slash, false) => '/',
        (Slash, true) => '?',
        _ => return None,
    };
    Some(ch.to_string())
}
