/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 100
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_line_comment = 2,
  sym_block_comment = 3,
  anon_sym_LT = 4,
  anon_sym_SLASH_GT = 5,
  anon_sym_GT = 6,
  anon_sym_LT_SLASH = 7,
  sym_tag_name = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_event_name = 11,
  sym_string = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  aux_sym__expression_content_token1 = 15,
  sym_text = 16,
  anon_sym_ATimport = 17,
  anon_sym_LPAREN = 18,
  anon_sym_COMMA = 19,
  anon_sym_RPAREN = 20,
  anon_sym_ATexport = 21,
  anon_sym_ATtheme = 22,
  anon_sym_ATkeyframes = 23,
  sym_pseudo_class = 24,
  anon_sym_COLON = 25,
  anon_sym_SEMI = 26,
  sym_style_property = 27,
  aux_sym_style_value_token1 = 28,
  sym_theme_token = 29,
  sym_number = 30,
  sym_source_file = 31,
  sym__item = 32,
  sym_element = 33,
  sym__child = 34,
  sym_attribute = 35,
  sym_attribute_value = 36,
  sym_expression = 37,
  sym_interpolation = 38,
  aux_sym__expression_content = 39,
  sym_directive = 40,
  sym_import_directive = 41,
  sym_export_directive = 42,
  sym_theme_directive = 43,
  sym_keyframes_directive = 44,
  sym_style_block = 45,
  sym_pseudo_style_block = 46,
  sym_style_body = 47,
  sym_pseudo_class_block = 48,
  sym_style_declaration = 49,
  sym_style_value = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_element_repeat1 = 52,
  aux_sym_element_repeat2 = 53,
  aux_sym_style_body_repeat1 = 54,
  aux_sym_style_value_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_event_name] = "event_name",
  [sym_string] = "string",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__expression_content_token1] = "_expression_content_token1",
  [sym_text] = "text",
  [anon_sym_ATimport] = "directive_name",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATexport] = "directive_name",
  [anon_sym_ATtheme] = "directive_name",
  [anon_sym_ATkeyframes] = "directive_name",
  [sym_pseudo_class] = "pseudo_class",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [sym_style_property] = "style_property",
  [aux_sym_style_value_token1] = "style_value_token1",
  [sym_theme_token] = "theme_token",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_element] = "element",
  [sym__child] = "_child",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_expression] = "expression",
  [sym_interpolation] = "interpolation",
  [aux_sym__expression_content] = "_expression_content",
  [sym_directive] = "directive",
  [sym_import_directive] = "import_directive",
  [sym_export_directive] = "export_directive",
  [sym_theme_directive] = "theme_directive",
  [sym_keyframes_directive] = "keyframes_directive",
  [sym_style_block] = "style_block",
  [sym_pseudo_style_block] = "pseudo_style_block",
  [sym_style_body] = "style_body",
  [sym_pseudo_class_block] = "pseudo_class_block",
  [sym_style_declaration] = "style_declaration",
  [sym_style_value] = "style_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_element_repeat2] = "element_repeat2",
  [aux_sym_style_body_repeat1] = "style_body_repeat1",
  [aux_sym_style_value_repeat1] = "style_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_event_name] = sym_event_name,
  [sym_string] = sym_string,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__expression_content_token1] = aux_sym__expression_content_token1,
  [sym_text] = sym_text,
  [anon_sym_ATimport] = anon_sym_ATimport,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATexport] = anon_sym_ATimport,
  [anon_sym_ATtheme] = anon_sym_ATimport,
  [anon_sym_ATkeyframes] = anon_sym_ATimport,
  [sym_pseudo_class] = sym_pseudo_class,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_style_property] = sym_style_property,
  [aux_sym_style_value_token1] = aux_sym_style_value_token1,
  [sym_theme_token] = sym_theme_token,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_element] = sym_element,
  [sym__child] = sym__child,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_expression] = sym_expression,
  [sym_interpolation] = sym_interpolation,
  [aux_sym__expression_content] = aux_sym__expression_content,
  [sym_directive] = sym_directive,
  [sym_import_directive] = sym_import_directive,
  [sym_export_directive] = sym_export_directive,
  [sym_theme_directive] = sym_theme_directive,
  [sym_keyframes_directive] = sym_keyframes_directive,
  [sym_style_block] = sym_style_block,
  [sym_pseudo_style_block] = sym_pseudo_style_block,
  [sym_style_body] = sym_style_body,
  [sym_pseudo_class_block] = sym_pseudo_class_block,
  [sym_style_declaration] = sym_style_declaration,
  [sym_style_value] = sym_style_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_element_repeat2] = aux_sym_element_repeat2,
  [aux_sym_style_body_repeat1] = aux_sym_style_body_repeat1,
  [aux_sym_style_value_repeat1] = aux_sym_style_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_event_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__expression_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATimport] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATexport] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATtheme] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATkeyframes] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo_class] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_style_property] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_style_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_theme_token] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym__child] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expression_content] = {
    .visible = false,
    .named = false,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_import_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_export_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_theme_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_keyframes_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_style_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo_style_block] = {
    .visible = true,
    .named = true,
  },
  [sym_style_body] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo_class_block] = {
    .visible = true,
    .named = true,
  },
  [sym_style_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_style_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_style_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_style_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_closing_name = 1,
  field_export = 2,
  field_name = 3,
  field_path = 4,
  field_property = 5,
  field_pseudo = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_closing_name] = "closing_name",
  [field_export] = "export",
  [field_name] = "name",
  [field_path] = "path",
  [field_property] = "property",
  [field_pseudo] = "pseudo",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 1},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_pseudo, 1},
  [3] =
    {field_name, 1},
  [4] =
    {field_value, 0},
  [5] =
    {field_pseudo, 0},
  [6] =
    {field_path, 2},
  [7] =
    {field_name, 2},
  [8] =
    {field_property, 0},
    {field_value, 2},
  [10] =
    {field_name, 0},
    {field_value, 2},
  [12] =
    {field_closing_name, 4},
    {field_name, 1},
  [14] =
    {field_export, 4},
    {field_path, 2},
  [16] =
    {field_closing_name, 5},
    {field_name, 1},
  [18] =
    {field_closing_name, 6},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 23,
  [28] = 22,
  [29] = 26,
  [30] = 24,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 33,
  [35] = 31,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 12,
  [44] = 13,
  [45] = 18,
  [46] = 20,
  [47] = 5,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 49,
  [54] = 50,
  [55] = 55,
  [56] = 6,
  [57] = 8,
  [58] = 9,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 62,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 75,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 77,
  [89] = 82,
  [90] = 80,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 87,
  [97] = 94,
  [98] = 93,
  [99] = 99,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 6,
        '#', 21,
        '\'', 8,
        '(', 103,
        ')', 105,
        ',', 104,
        '-', 115,
        '/', 10,
        ':', 110,
        ';', 111,
        '<', 33,
        '=', 38,
        '>', 35,
        '@', 15,
        '{', 64,
        '}', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(121);
      if (lookahead == '-') ADVANCE(116);
      if (lookahead == '/') ADVANCE(122);
      if (lookahead == ':') ADVANCE(129);
      if (lookahead == ';') ADVANCE(111);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(130);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(121);
      if (lookahead == '-') ADVANCE(128);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == ';') ADVANCE(111);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(35);
      if (lookahead == '@') ADVANCE(20);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == 'i') ADVANCE(49);
      if (lookahead == 'k') ADVANCE(41);
      if (lookahead == 't') ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 17:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 19:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 20:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '<') ADVANCE(32);
      if (lookahead == '@') ADVANCE(76);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'a') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'e') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'f') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'h') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'm') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'm') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'm') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'o') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'o') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'p') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'p') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'r') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'r') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'r') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 's') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 't') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 't') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'x') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_event_name);
      if (lookahead == 'y') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_event_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym__expression_content_token1);
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__expression_content_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__expression_content_token1);
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '\'') ADVANCE(69);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__expression_content_token1);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(66);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__expression_content_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '<') ADVANCE(32);
      if (lookahead == '@') ADVANCE(76);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '*') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(97);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '*') ADVANCE(100);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(97);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'a') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'e') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'e') ADVANCE(95);
      if (lookahead == 'i') ADVANCE(84);
      if (lookahead == 'k') ADVANCE(77);
      if (lookahead == 't') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'e') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'e') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'f') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'h') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'm') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'm') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'm') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'p') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'p') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'r') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'r') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'r') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 's') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 't') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 't') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'x') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead == 'y') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(97);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '{') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(100);
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(100);
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '/') ADVANCE(101);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(100);
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '/') ADVANCE(101);
      if (lookahead == '<' ||
          lookahead == '>' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(100);
      if (lookahead != 0) ADVANCE(100);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_ATimport);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_ATexport);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_ATtheme);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_ATkeyframes);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_pseudo_class);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_style_property);
      if (lookahead == '%') ADVANCE(135);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_style_property);
      if (lookahead == '%') ADVANCE(135);
      if (lookahead == '.') ADVANCE(127);
      if (lookahead == '-' ||
          lookahead == '_') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_style_property);
      if (lookahead == '%') ADVANCE(135);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(117);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_style_property);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_style_property);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_style_property);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(121);
      if (lookahead == '-') ADVANCE(116);
      if (lookahead == '/') ADVANCE(122);
      if (lookahead == ':') ADVANCE(129);
      if (lookahead == ';') ADVANCE(111);
      if (lookahead == '}') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(117);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(130);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(120);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '\'') ADVANCE(121);
      if (lookahead == '-') ADVANCE(128);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '"') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(125);
      if (lookahead == '\n' ||
          lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '\'') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(126);
      if (lookahead == '\n' ||
          lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(121);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '*') ADVANCE(124);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '*') ADVANCE(123);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\n' ||
          lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '*') ADVANCE(123);
      if (lookahead == '\n' ||
          lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(120);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead == '#' ||
          lookahead == ';' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(121);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_style_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_theme_token);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (lookahead == '%' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (lookahead == '%' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      if (lookahead == '%' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 24},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 24},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 24},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 13},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 16},
  [76] = {.lex_state = 17},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 16},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 16},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 17},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 16},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 16},
  [94] = {.lex_state = 16},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 16},
  [98] = {.lex_state = 16},
  [99] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [sym_event_name] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_ATimport] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATexport] = ACTIONS(1),
    [anon_sym_ATtheme] = ACTIONS(1),
    [anon_sym_ATkeyframes] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_style_property] = ACTIONS(1),
    [sym_theme_token] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(92),
    [sym__item] = STATE(2),
    [sym_element] = STATE(2),
    [sym_interpolation] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_import_directive] = STATE(21),
    [sym_export_directive] = STATE(21),
    [sym_theme_directive] = STATE(21),
    [sym_keyframes_directive] = STATE(21),
    [sym_style_block] = STATE(2),
    [sym_pseudo_style_block] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(7),
    [sym_block_comment] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_text] = ACTIONS(7),
    [anon_sym_ATimport] = ACTIONS(13),
    [anon_sym_ATexport] = ACTIONS(15),
    [anon_sym_ATtheme] = ACTIONS(17),
    [anon_sym_ATkeyframes] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_ATimport,
    ACTIONS(15), 1,
      anon_sym_ATexport,
    ACTIONS(17), 1,
      anon_sym_ATtheme,
    ACTIONS(19), 1,
      anon_sym_ATkeyframes,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(21), 4,
      sym_import_directive,
      sym_export_directive,
      sym_theme_directive,
      sym_keyframes_directive,
    STATE(3), 7,
      sym__item,
      sym_element,
      sym_interpolation,
      sym_directive,
      sym_style_block,
      sym_pseudo_style_block,
      aux_sym_source_file_repeat1,
  [45] = 11,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_ATimport,
    ACTIONS(42), 1,
      anon_sym_ATexport,
    ACTIONS(45), 1,
      anon_sym_ATtheme,
    ACTIONS(48), 1,
      anon_sym_ATkeyframes,
    ACTIONS(30), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(21), 4,
      sym_import_directive,
      sym_export_directive,
      sym_theme_directive,
      sym_keyframes_directive,
    STATE(3), 7,
      sym__item,
      sym_element,
      sym_interpolation,
      sym_directive,
      sym_style_block,
      sym_pseudo_style_block,
      aux_sym_source_file_repeat1,
  [90] = 2,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [106] = 2,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [122] = 2,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [138] = 2,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [154] = 2,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [170] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [186] = 2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [202] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [218] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [234] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [250] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [266] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [282] = 3,
    STATE(17), 1,
      aux_sym_style_value_repeat1,
    ACTIONS(101), 4,
      sym_string,
      aux_sym_style_value_token1,
      sym_theme_token,
      sym_number,
    ACTIONS(99), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      anon_sym_SEMI,
      sym_style_property,
  [300] = 3,
    STATE(17), 1,
      aux_sym_style_value_repeat1,
    ACTIONS(105), 4,
      sym_string,
      aux_sym_style_value_token1,
      sym_theme_token,
      sym_number,
    ACTIONS(103), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      anon_sym_SEMI,
      sym_style_property,
  [318] = 2,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [334] = 2,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [350] = 2,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [366] = 2,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 10,
      sym_line_comment,
      sym_block_comment,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
      anon_sym_ATimport,
      anon_sym_ATexport,
      anon_sym_ATtheme,
      anon_sym_ATkeyframes,
  [382] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(128), 1,
      anon_sym_LT_SLASH,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(24), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [403] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(128), 1,
      anon_sym_LT_SLASH,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(132), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(25), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [424] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 1,
      anon_sym_LT_SLASH,
    ACTIONS(132), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(25), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [445] = 5,
    ACTIONS(139), 1,
      anon_sym_LT,
    ACTIONS(142), 1,
      anon_sym_LT_SLASH,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(25), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [466] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      anon_sym_LT_SLASH,
    ACTIONS(147), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(23), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [487] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 1,
      anon_sym_LT_SLASH,
    ACTIONS(132), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(25), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [508] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 1,
      anon_sym_LT_SLASH,
    ACTIONS(153), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(30), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [529] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      anon_sym_LT_SLASH,
    ACTIONS(155), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(27), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [550] = 5,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 1,
      anon_sym_LT_SLASH,
    ACTIONS(132), 3,
      sym_line_comment,
      sym_block_comment,
      sym_text,
    STATE(25), 4,
      sym_element,
      sym__child,
      sym_interpolation,
      aux_sym_element_repeat2,
  [571] = 5,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      sym_pseudo_class,
    ACTIONS(161), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(167), 2,
      sym_style_property,
      sym_theme_token,
    STATE(33), 3,
      sym_pseudo_class_block,
      sym_style_declaration,
      aux_sym_style_body_repeat1,
  [591] = 5,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    ACTIONS(174), 1,
      sym_pseudo_class,
    ACTIONS(169), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(177), 2,
      sym_style_property,
      sym_theme_token,
    STATE(32), 3,
      sym_pseudo_class_block,
      sym_style_declaration,
      aux_sym_style_body_repeat1,
  [611] = 5,
    ACTIONS(165), 1,
      sym_pseudo_class,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 2,
      sym_style_property,
      sym_theme_token,
    ACTIONS(180), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(32), 3,
      sym_pseudo_class_block,
      sym_style_declaration,
      aux_sym_style_body_repeat1,
  [631] = 5,
    ACTIONS(165), 1,
      sym_pseudo_class,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 2,
      sym_style_property,
      sym_theme_token,
    ACTIONS(180), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(32), 3,
      sym_pseudo_class_block,
      sym_style_declaration,
      aux_sym_style_body_repeat1,
  [651] = 5,
    ACTIONS(165), 1,
      sym_pseudo_class,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 2,
      sym_style_property,
      sym_theme_token,
    ACTIONS(186), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(34), 3,
      sym_pseudo_class_block,
      sym_style_declaration,
      aux_sym_style_body_repeat1,
  [671] = 5,
    ACTIONS(195), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_expression,
    ACTIONS(190), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
    ACTIONS(192), 2,
      sym_attribute_name,
      sym_event_name,
    STATE(36), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [690] = 6,
    ACTIONS(198), 1,
      anon_sym_SLASH_GT,
    ACTIONS(200), 1,
      anon_sym_GT,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_expression,
    ACTIONS(202), 2,
      sym_attribute_name,
      sym_event_name,
    STATE(36), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [711] = 6,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    ACTIONS(206), 1,
      anon_sym_SLASH_GT,
    ACTIONS(208), 1,
      anon_sym_GT,
    STATE(64), 1,
      sym_expression,
    ACTIONS(202), 2,
      sym_attribute_name,
      sym_event_name,
    STATE(37), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [732] = 6,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    ACTIONS(210), 1,
      anon_sym_SLASH_GT,
    ACTIONS(212), 1,
      anon_sym_GT,
    STATE(64), 1,
      sym_expression,
    ACTIONS(202), 2,
      sym_attribute_name,
      sym_event_name,
    STATE(40), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [753] = 6,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_SLASH_GT,
    ACTIONS(216), 1,
      anon_sym_GT,
    STATE(64), 1,
      sym_expression,
    ACTIONS(202), 2,
      sym_attribute_name,
      sym_event_name,
    STATE(36), 2,
      sym_attribute,
      aux_sym_element_repeat1,
  [774] = 2,
    ACTIONS(220), 1,
      anon_sym_SEMI,
    ACTIONS(218), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      sym_style_property,
      sym_theme_token,
  [786] = 3,
    STATE(16), 1,
      aux_sym_style_value_repeat1,
    STATE(41), 1,
      sym_style_value,
    ACTIONS(222), 4,
      sym_string,
      aux_sym_style_value_token1,
      sym_theme_token,
      sym_number,
  [799] = 1,
    ACTIONS(83), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      sym_style_property,
      sym_theme_token,
  [808] = 1,
    ACTIONS(89), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [817] = 1,
    ACTIONS(110), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [826] = 1,
    ACTIONS(118), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [835] = 1,
    ACTIONS(57), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [844] = 1,
    ACTIONS(224), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      sym_style_property,
      sym_theme_token,
  [853] = 4,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(51), 2,
      sym_expression,
      aux_sym__expression_content,
  [868] = 4,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(51), 2,
      sym_expression,
      aux_sym__expression_content,
  [883] = 4,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    ACTIONS(234), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(51), 2,
      sym_expression,
      aux_sym__expression_content,
  [898] = 1,
    ACTIONS(242), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      sym_style_property,
      sym_theme_token,
  [907] = 4,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(51), 2,
      sym_expression,
      aux_sym__expression_content,
  [922] = 4,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(51), 2,
      sym_expression,
      aux_sym__expression_content,
  [937] = 2,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(248), 5,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
      sym_event_name,
      anon_sym_LBRACE,
  [948] = 1,
    ACTIONS(59), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_RBRACE,
      sym_pseudo_class,
      sym_style_property,
      sym_theme_token,
  [957] = 1,
    ACTIONS(69), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [966] = 1,
    ACTIONS(73), 6,
      sym_line_comment,
      sym_block_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_text,
  [975] = 3,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(252), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(50), 2,
      sym_expression,
      aux_sym__expression_content,
  [987] = 1,
    ACTIONS(254), 5,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
      sym_event_name,
      anon_sym_LBRACE,
  [995] = 3,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(54), 2,
      sym_expression,
      aux_sym__expression_content,
  [1007] = 1,
    ACTIONS(258), 5,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
      sym_event_name,
      anon_sym_LBRACE,
  [1015] = 3,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(260), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(53), 2,
      sym_expression,
      aux_sym__expression_content,
  [1027] = 1,
    ACTIONS(262), 5,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
      sym_event_name,
      anon_sym_LBRACE,
  [1035] = 1,
    ACTIONS(264), 5,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_attribute_name,
      sym_event_name,
      anon_sym_LBRACE,
  [1043] = 3,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
    ACTIONS(266), 2,
      sym_string,
      aux_sym__expression_content_token1,
    STATE(49), 2,
      sym_expression,
      aux_sym__expression_content,
  [1055] = 1,
    ACTIONS(268), 4,
      sym_string,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__expression_content_token1,
  [1062] = 4,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
    ACTIONS(270), 1,
      sym_string,
    STATE(60), 1,
      sym_expression,
    STATE(65), 1,
      sym_attribute_value,
  [1075] = 3,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    ACTIONS(274), 1,
      sym_pseudo_class,
    STATE(14), 1,
      sym_style_body,
  [1085] = 2,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
  [1092] = 2,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_style_body,
  [1099] = 2,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_style_body,
  [1106] = 2,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_style_body,
  [1113] = 2,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_style_body,
  [1120] = 1,
    ACTIONS(282), 1,
      sym_tag_name,
  [1124] = 1,
    ACTIONS(284), 1,
      sym_identifier,
  [1128] = 1,
    ACTIONS(286), 1,
      anon_sym_GT,
  [1132] = 1,
    ACTIONS(288), 1,
      sym_tag_name,
  [1136] = 1,
    ACTIONS(290), 1,
      sym_string,
  [1140] = 1,
    ACTIONS(292), 1,
      sym_tag_name,
  [1144] = 1,
    ACTIONS(294), 1,
      sym_string,
  [1148] = 1,
    ACTIONS(296), 1,
      anon_sym_GT,
  [1152] = 1,
    ACTIONS(298), 1,
      sym_string,
  [1156] = 1,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
  [1160] = 1,
    ACTIONS(302), 1,
      anon_sym_LPAREN,
  [1164] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [1168] = 1,
    ACTIONS(306), 1,
      anon_sym_GT,
  [1172] = 1,
    ACTIONS(308), 1,
      anon_sym_GT,
  [1176] = 1,
    ACTIONS(310), 1,
      anon_sym_GT,
  [1180] = 1,
    ACTIONS(312), 1,
      sym_tag_name,
  [1184] = 1,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
  [1188] = 1,
    ACTIONS(316), 1,
      ts_builtin_sym_end,
  [1192] = 1,
    ACTIONS(318), 1,
      sym_tag_name,
  [1196] = 1,
    ACTIONS(320), 1,
      sym_tag_name,
  [1200] = 1,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
  [1204] = 1,
    ACTIONS(324), 1,
      anon_sym_GT,
  [1208] = 1,
    ACTIONS(326), 1,
      sym_tag_name,
  [1212] = 1,
    ACTIONS(328), 1,
      sym_tag_name,
  [1216] = 1,
    ACTIONS(330), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 106,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 138,
  [SMALL_STATE(8)] = 154,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 186,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 234,
  [SMALL_STATE(14)] = 250,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 282,
  [SMALL_STATE(17)] = 300,
  [SMALL_STATE(18)] = 318,
  [SMALL_STATE(19)] = 334,
  [SMALL_STATE(20)] = 350,
  [SMALL_STATE(21)] = 366,
  [SMALL_STATE(22)] = 382,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 424,
  [SMALL_STATE(25)] = 445,
  [SMALL_STATE(26)] = 466,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 508,
  [SMALL_STATE(29)] = 529,
  [SMALL_STATE(30)] = 550,
  [SMALL_STATE(31)] = 571,
  [SMALL_STATE(32)] = 591,
  [SMALL_STATE(33)] = 611,
  [SMALL_STATE(34)] = 631,
  [SMALL_STATE(35)] = 651,
  [SMALL_STATE(36)] = 671,
  [SMALL_STATE(37)] = 690,
  [SMALL_STATE(38)] = 711,
  [SMALL_STATE(39)] = 732,
  [SMALL_STATE(40)] = 753,
  [SMALL_STATE(41)] = 774,
  [SMALL_STATE(42)] = 786,
  [SMALL_STATE(43)] = 799,
  [SMALL_STATE(44)] = 808,
  [SMALL_STATE(45)] = 817,
  [SMALL_STATE(46)] = 826,
  [SMALL_STATE(47)] = 835,
  [SMALL_STATE(48)] = 844,
  [SMALL_STATE(49)] = 853,
  [SMALL_STATE(50)] = 868,
  [SMALL_STATE(51)] = 883,
  [SMALL_STATE(52)] = 898,
  [SMALL_STATE(53)] = 907,
  [SMALL_STATE(54)] = 922,
  [SMALL_STATE(55)] = 937,
  [SMALL_STATE(56)] = 948,
  [SMALL_STATE(57)] = 957,
  [SMALL_STATE(58)] = 966,
  [SMALL_STATE(59)] = 975,
  [SMALL_STATE(60)] = 987,
  [SMALL_STATE(61)] = 995,
  [SMALL_STATE(62)] = 1007,
  [SMALL_STATE(63)] = 1015,
  [SMALL_STATE(64)] = 1027,
  [SMALL_STATE(65)] = 1035,
  [SMALL_STATE(66)] = 1043,
  [SMALL_STATE(67)] = 1055,
  [SMALL_STATE(68)] = 1062,
  [SMALL_STATE(69)] = 1075,
  [SMALL_STATE(70)] = 1085,
  [SMALL_STATE(71)] = 1092,
  [SMALL_STATE(72)] = 1099,
  [SMALL_STATE(73)] = 1106,
  [SMALL_STATE(74)] = 1113,
  [SMALL_STATE(75)] = 1120,
  [SMALL_STATE(76)] = 1124,
  [SMALL_STATE(77)] = 1128,
  [SMALL_STATE(78)] = 1132,
  [SMALL_STATE(79)] = 1136,
  [SMALL_STATE(80)] = 1140,
  [SMALL_STATE(81)] = 1144,
  [SMALL_STATE(82)] = 1148,
  [SMALL_STATE(83)] = 1152,
  [SMALL_STATE(84)] = 1156,
  [SMALL_STATE(85)] = 1160,
  [SMALL_STATE(86)] = 1164,
  [SMALL_STATE(87)] = 1168,
  [SMALL_STATE(88)] = 1172,
  [SMALL_STATE(89)] = 1176,
  [SMALL_STATE(90)] = 1180,
  [SMALL_STATE(91)] = 1184,
  [SMALL_STATE(92)] = 1188,
  [SMALL_STATE(93)] = 1192,
  [SMALL_STATE(94)] = 1196,
  [SMALL_STATE(95)] = 1200,
  [SMALL_STATE(96)] = 1204,
  [SMALL_STATE(97)] = 1208,
  [SMALL_STATE(98)] = 1212,
  [SMALL_STATE(99)] = 1216,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_directive, 4, 0, 6),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_directive, 4, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 8, 0, 13),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 8, 0, 13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_body, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_body, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo_style_block, 3, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pseudo_style_block, 3, 0, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theme_directive, 3, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_theme_directive, 3, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyframes_directive, 3, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyframes_directive, 3, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_body, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_body, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_block, 2, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_block, 2, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_directive, 4, 0, 7),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_directive, 4, 0, 7),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_value, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_style_value_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_style_value_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 6, 0, 10),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 6, 0, 10),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_directive, 6, 0, 11),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_directive, 6, 0, 11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 7, 0, 12),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 7, 0, 12),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(25),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(90),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat2, 2, 0, 0), SHIFT_REPEAT(59),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_body_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_style_body_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_body_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_style_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_declaration, 3, 0, 8),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_declaration, 4, 0, 8),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_content, 2, 0, 0), SHIFT_REPEAT(51),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expression_content, 2, 0, 0), SHIFT_REPEAT(66),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expression_content, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo_class_block, 2, 0, 5),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 4),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 9),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [316] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_uix(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "uix",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
