//! 帧命令、执行审计与呈现契约 — encoder 子模块。
//!
//! 有序命令流（[`FrameCommand`] / [`FrameRasterOp`]）、CPU 光栅来源审计
//! （[`GpuFrameAudit`]）与最终提交边界（[`FramePresenter`] / [`ReferenceFrame`]）。

use crate::draw::Color;

use super::geometry::{
    FrameGlyphBlit, FrameImage, FrameOpacity, FrameRadius, FrameRect, FrameSampledRect,
    FrameStrokeRect,
};

/// API-neutral raster work.  More operations can be added without changing
/// frame ordering or the presentation contract.
///
/// 目标相关操作（[`Self::FillRectAdditive`]、
/// [`Self::FillRoundedRectAdditive`]、Additive [`Self::StrokeRoundedRects`]、
/// [`Self::ScrollCopy`]）必须直接作用于
/// 累积目标（Native 命令或参考执行器）。把它们录进透明 CPU segment 后再做
/// source-over 合成并不等价，禁止作为替代实现。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FrameRasterOp {
    FillRect {
        rect: FrameRect,
        color: Color,
    },
    /// 使用共享 SDF coverage 对圆角区域执行普通 SrcOver 填充。
    FillRoundedRect {
        rect: FrameRect,
        color: Color,
        radius: FrameRadius,
    },
    /// 使用原始圆角几何，仅以整数 surface-space 矩形硬裁剪 SrcOver 覆盖。
    /// `radius == 0` 时同时承载普通矩形的 clipped fast path。
    FillRoundedRectClipped {
        rect: FrameRect,
        color: Color,
        radius: FrameRadius,
        clip: FrameRect,
    },
    /// Ordered SrcOver glyph coverage blits sharing one integer surface clip.
    BlitGlyphs {
        glyphs: Vec<FrameGlyphBlit>,
        clip: FrameRect,
    },
    /// Ordered centered rectangle strokes sharing one surface clip and blend fact.
    StrokeRoundedRects {
        strokes: Vec<FrameStrokeRect>,
        clip: FrameRect,
        /// 为 true 时逐通道饱和加到累计目标；为 false 时使用普通 SrcOver。
        additive: bool,
    },
    /// Channel-wise saturating add into the destination (CPU Additive blend).
    FillRectAdditive {
        rect: FrameRect,
        color: Color,
        /// 把目标相关填充限制在已经验证的 surface-space 整数矩形内。
        clip: FrameRect,
    },
    /// 使用共享 SDF coverage 对圆角区域执行逐通道饱和加法。
    FillRoundedRectAdditive {
        rect: FrameRect,
        color: Color,
        radius: FrameRadius,
        /// 保留圆角原始几何，仅由该 surface-space 矩形裁剪最终覆盖。
        clip: FrameRect,
    },
    /// 把 `viewport` 中按 `(dx, dy)` 平移后的像素复制回同一视口；
    /// 语义与 [`crate::draw::Canvas2D::scroll_region`] 一致，位移取整。
    ScrollCopy {
        viewport: FrameRect,
        dx: i32,
        dy: i32,
    },
}

/// A single ordered frame command.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FrameCommand {
    Clear {
        color: Color,
    },
    Native {
        operation: FrameRasterOp,
    },
    CpuSegment {
        image: FrameImage,
        src: FrameRect,
        dst: FrameRect,
    },
    PictureBlit {
        image: FrameImage,
        src: FrameRect,
        dst: FrameSampledRect,
        opacity: FrameOpacity,
        /// 父画布 Additive 时为 true；严格 GPU 走 One+One 纹理 pipeline。
        additive: bool,
    },
}

/// CPU-produced raster payloads that are forbidden by a GPU-native frame.
///
/// Source images loaded by the application are not classified here: this
/// audit only tracks pixels generated by UI rasterization or Picture
/// materialization inside the draw pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuFrameViolationKind {
    CpuRasterSegment,
    CpuGlyphCoverage,
    MaterializedPicture,
}

impl std::fmt::Display for GpuFrameViolationKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::CpuRasterSegment => "CPU raster segment",
            Self::CpuGlyphCoverage => "CPU-rasterized glyph coverage",
            Self::MaterializedPicture => "CPU-materialized Picture",
        })
    }
}

/// Allocation-free audit of one encoded frame's raster provenance.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct GpuFrameAudit {
    pub cpu_raster_segments: usize,
    pub cpu_raster_bytes: usize,
    pub cpu_glyphs: usize,
    pub cpu_glyph_bytes: usize,
    pub materialized_pictures: usize,
    pub materialized_picture_bytes: usize,
}

impl GpuFrameAudit {
    pub const fn is_gpu_native(self) -> bool {
        self.cpu_raster_segments == 0 && self.cpu_glyphs == 0 && self.materialized_pictures == 0
    }

    pub const fn first_violation(self) -> Option<GpuFrameViolationKind> {
        if self.cpu_raster_segments != 0 {
            Some(GpuFrameViolationKind::CpuRasterSegment)
        } else if self.cpu_glyphs != 0 {
            Some(GpuFrameViolationKind::CpuGlyphCoverage)
        } else if self.materialized_pictures != 0 {
            Some(GpuFrameViolationKind::MaterializedPicture)
        } else {
            None
        }
    }
}

/// Result of one successful final presentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PresentOutcome {
    Presented,
}

/// Result of asking a backend to execute an encoded Picture. Backends that do
/// not have a lossless executor explicitly return `Unsupported`; compositor
/// code then retains its normal DisplayList replay path rather than silently
/// changing the raster contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodedPictureExecution {
    Executed,
    Unsupported,
}

/// Result of asking a backend to execute the complete main-surface command
/// stream. Unlike [`EncodedPictureExecution`], this target is the frame that
/// will reach the sole final presenter; execution itself must not present.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodedFrameExecution {
    Executed,
    Unsupported,
}

/// The sole final-submission boundary for an encoded frame.
pub trait FramePresenter {
    type Error;

    fn present(&mut self, frame: &ReferenceFrame) -> Result<PresentOutcome, Self::Error>;
}

/// Immutable, API-neutral frame produced by the in-memory reference executor.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReferenceFrame {
    pub(crate) width: i32,
    pub(crate) height: i32,
    pub(crate) pixels: Vec<u32>,
}

impl ReferenceFrame {
    pub const fn width(&self) -> i32 {
        self.width
    }

    pub const fn height(&self) -> i32 {
        self.height
    }

    pub fn pixels(&self) -> &[u32] {
        &self.pixels
    }

    pub fn pixel(&self, x: i32, y: i32) -> Option<u32> {
        if x < 0 || y < 0 || x >= self.width || y >= self.height {
            return None;
        }
        self.pixels
            .get((y as usize).saturating_mul(self.width as usize) + x as usize)
            .copied()
    }
}
