[package]
name = "uix-lang-cli"
version = "0.0.2"
edition = "2024"
publish = false
license-file = "../LICENSE"
description = "UIX Lang command-line toolchain adapter"

[dependencies]
proc-macro2 = "1"
quote = "1"
serde_json = "1"
syn = { version = "2", features = ["full"] }
uix-lang-compiler = { path = "../uix-lang-compiler", version = "0.0.2" }
