#!/usr/bin/env python3
"""Extract inline #[cfg(test)] mod tests { ... } blocks into src/tests/."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
TESTS = SRC / "tests"


def module_path(rel: Path) -> str:
    parts = rel.with_suffix("").parts
    if parts and parts[0] == "src":
        parts = parts[1:]
    return "::".join(parts)


def find_test_mod_block(content: str) -> tuple[int, int] | None:
    marker = "#[cfg(test)]"
    idx = content.rfind(marker)
    if idx == -1:
        return None
    rest = content[idx:]
    if not re.match(r"#\[cfg\(test\)\]\s*\nmod tests\s*\{", rest):
        return None
    open_brace = content.find("{", idx)
    if open_brace == -1:
        return None
    depth = 0
    for i in range(open_brace, len(content)):
        ch = content[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return idx, i + 1
    return None


def transform_body(body: str, _mod_path: str) -> str:
    # Tests are included via #[path] as child modules; `use super::*` reaches the parent.
    return body.strip() + "\n"


def extract_from_file(path: Path) -> bool:
    rel = path.relative_to(SRC)
    content = path.read_text(encoding="utf-8")
    span = find_test_mod_block(content)
    if span is None:
        return False
    start, end = span
    block = content[start:end]
    m = re.search(r"mod tests\s*\{(.*)\}\s*$", block, re.DOTALL)
    if not m:
        return False
    body = transform_body(m.group(1), module_path(Path("src") / rel))
    dest = TESTS / rel.with_suffix(".rs")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body, encoding="utf-8", newline="\n")
    new_content = content[:start].rstrip() + "\n"
    path.write_text(new_content, encoding="utf-8", newline="\n")
    print(f"extracted {rel} -> {dest.relative_to(ROOT)}")
    return True


def wire_test_path(source: Path) -> None:
    rel = source.relative_to(SRC)
    test_file = TESTS / rel.with_suffix(".rs")
    if not test_file.exists():
        return
    attr = "../" * len(rel.parts) + f"tests/{rel.as_posix()}"
    content = source.read_text(encoding="utf-8").rstrip() + "\n"
    if "#[path =" in content and "mod tests;" in content:
        return
    content += f'\n#[cfg(test)]\n#[path = "{attr}"]\nmod tests;\n'
    source.write_text(content, encoding="utf-8", newline="\n")


def move_external_test(src: Path, dest_rel: Path) -> None:
    dest = TESTS / dest_rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = src.read_text(encoding="utf-8")
    mod_path = "::".join(dest_rel.with_suffix("").parts)
    if "use super::*;" in body:
        body = body.replace("use super::*;", f"use crate::{mod_path}::*;", 1)
    dest.write_text(body, encoding="utf-8", newline="\n")
    src.unlink()
    print(f"moved {src.relative_to(ROOT)} -> {dest.relative_to(ROOT)}")


def collect_test_files(base: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(base.rglob("*.rs")):
        if path.is_relative_to(TESTS):
            continue
        if path.name.endswith("_tests.rs") or path.name == "tests.rs":
            continue
        text = path.read_text(encoding="utf-8")
        if "#[cfg(test)]" in text and "mod tests" in text:
            files.append(path)
    return files


def write_mod_tree(dir_path: Path, root: Path) -> None:
    if not dir_path.exists():
        return
    children_dirs = sorted(p for p in dir_path.iterdir() if p.is_dir())
    children_rs = sorted(
        p for p in dir_path.iterdir() if p.is_file() and p.suffix == ".rs" and p.name != "mod.rs"
    )
    lines = [
        "// @generated by scripts/extract_tests.py",
        "",
    ]
    for d in children_dirs:
        lines.append(f"mod {d.name};")
    for f in children_rs:
        lines.append(f"mod {f.stem};")
    lines.append("")
    (dir_path / "mod.rs").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    for d in children_dirs:
        write_mod_tree(d, root)


def main() -> None:
    if TESTS.exists():
        import shutil

        shutil.rmtree(TESTS)
    TESTS.mkdir()

    count = 0
    for path in collect_test_files(SRC):
        if extract_from_file(path):
            count += 1
            wire_test_path(path)

    # Already-external unit test modules.
    style_tests = SRC / "ui" / "foundation" / "style" / "tests.rs"
    if style_tests.exists():
        move_external_test(style_tests, Path("ui/foundation/style.rs"))
        style_mod = SRC / "ui" / "foundation" / "style" / "mod.rs"
        text = style_mod.read_text(encoding="utf-8")
        text = re.sub(r"\n#\[cfg\(test\)\]\nmod tests;\n", "\n", text)
        style_mod.write_text(text, encoding="utf-8", newline="\n")
        wire_test_path(SRC / "ui" / "foundation" / "style" / "mod.rs")

    tree_tests = SRC / "ui" / "core" / "widget" / "tree_core_tests.rs"
    if tree_tests.exists():
        body = tree_tests.read_text(encoding="utf-8")
        body = body.replace("use super::*;", "use crate::ui::core::widget::tree_core::*;", 1)
        dest = TESTS / "ui" / "core" / "widget" / "tree_core.rs"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body, encoding="utf-8", newline="\n")
        tree_tests.unlink()
        tree_core = SRC / "ui" / "core" / "widget" / "tree_core.rs"
        text = tree_core.read_text(encoding="utf-8")
        text = re.sub(
            r"\n#\[cfg\(test\)\]\n#\[path = \"tree_core_tests\.rs\"\]\nmod tests;\n",
            "\n",
            text,
        )
        tree_core.write_text(text, encoding="utf-8", newline="\n")
        wire_test_path(tree_core)
        print(f"moved tree_core_tests.rs -> {dest.relative_to(ROOT)}")

    orphan = SRC / "ui" / "core" / "widget" / "tree_core_tests_extra.rs"
    if orphan.exists():
        orphan.unlink()
        print(f"removed orphan {orphan.relative_to(ROOT)}")

    write_mod_tree(TESTS, ROOT)

    lib = SRC / "lib.rs"
    lib_text = lib.read_text(encoding="utf-8")
    if "#[cfg(test)]\nmod tests;" not in lib_text:
        lib_text = lib_text.rstrip() + "\n\n#[cfg(test)]\nmod tests;\n"
        lib.write_text(lib_text, encoding="utf-8", newline="\n")

    print(f"done: {count} inline modules extracted")


if __name__ == "__main__":
    main()
