use std::sync::Arc;

use crate::draw::geometry::spatial::PhysicalUnit;
use crate::draw::Color;
use crate::native::capabilities::system::StatusLevel;
use crate::native::windowing::input::{ControlSize, ScrollDirection};
use crate::ui::form::FormLayout;
use crate::ui::layout::{AlignItems, FlexDirection, JustifyContent};
use crate::ui::theme::style::{Style, StyleSet};
use crate::ui::widgets::window_chrome::WindowControl;
use crate::ui::widgets::*;
use crate::ui::Placement;

use super::{
    SnapshotCollapsePanel, SnapshotField, SnapshotPopconfirm, SnapshotTransferItem,
    SnapshotTreeNode,
};
// 表格 capability 启用时才引入专属快照列模型。
#[cfg(feature = "table")]
// 两个类型只服务同步门控的 Table 枚举变体。
use super::{SnapshotTableColumn, SnapshotTableColumnGroup};

mod accessibility;

#[derive(Debug, Clone, PartialEq)]
pub enum SnapshotFields {
    Unknown,
    Custom {
        widget: &'static str,
        fields: Vec<SnapshotField>,
    },
    Button {
        text: String,
        disabled: bool,
        block: bool,
        loading: bool,
        icon: String,
        group_position: Option<ButtonGroupPosition>,
        style_set: Arc<StyleSet>,
        style: Arc<Style>,
    },
    WindowControl {
        control: WindowControl,
        accessible_name: String,
    },
    Label {
        text: String,
        font_size: f32,
        font_size_unit: Option<PhysicalUnit>,
        color: Option<Color>,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
        style: Option<Style>,
    },
    Input {
        placeholder: String,
        input_size: ControlSize,
        disabled: bool,
        prefix: String,
        suffix: String,
        addon_before: String,
        addon_after: String,
        password: bool,
        password_visible: bool,
        clearable: bool,
        search: bool,
        status: Option<InputStatus>,
        status_message: String,
        textarea: bool,
        textarea_rows: usize,
        max_length: Option<usize>,
    },
    Space {
        direction: FlexDirection,
        space_size: SpaceSize,
        wrap: bool,
        justify: JustifyContent,
        align: AlignItems,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
        flex_grow: f32,
    },
    Divider {
        text: Option<String>,
        orientation: DividerOrientation,
        direction: DividerDirection,
        color: Option<Color>,
        text_size: f32,
        dashed: bool,
    },
    Icon {
        name: String,
        size: f32,
    },
    Typography {
        content: String,
        type_: TypographyType,
        disabled: bool,
        mark: bool,
        code: bool,
        underline: bool,
        delete: bool,
        strong: bool,
        italic: bool,
        copyable: bool,
        color_override: Option<Color>,
    },
    Checkbox {
        checked: bool,
        disabled: bool,
        label: String,
    },
    Radio {
        group_name: String,
        options: Vec<String>,
        selected: usize,
        disabled: bool,
        direction: RadioDirection,
        item_h: f32,
    },
    Switch {
        checked: bool,
        disabled: bool,
        size: f32,
    },
    Slider {
        min: f64,
        max: f64,
        step: f64,
        value: f64,
        marks: Vec<(f64, String)>,
        tooltip: Option<crate::ui::widgets::TooltipPlacement>,
    },
    RangeSlider {
        min: f64,
        max: f64,
        step: f64,
        start: f64,
        end: f64,
        active_thumb: RangeSliderThumb,
        size: ControlSize,
    },
    Rate {
        count: usize,
        value: usize,
        half: bool,
        disabled: bool,
        clearable: bool,
        character: String,
    },
    InputNumber {
        value: f64,
        min: f64,
        max: f64,
        step: f64,
        placeholder: String,
        disabled: bool,
        keyboard: bool,
        formatted: bool,
        display_value: Option<String>,
    },
    Avatar {
        text: String,
        size: f32,
        bg_color: Option<Color>,
        text_color: Option<Color>,
        square: bool,
        src: String,
    },
    Badge {
        count: i32,
        max: i32,
        dot: bool,
        color: Option<Color>,
        adaptive_foreground: bool,
        ribbon: bool,
        size: f32,
        status: Option<BadgeStatus>,
        show_zero: bool,
        text: String,
        offset_x: f32,
        offset_y: f32,
        offset_unit: Option<(PhysicalUnit, PhysicalUnit)>,
    },
    Card {
        title: Option<String>,
        bordered: bool,
        hoverable: bool,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
        padding: f32,
        elevation: u8,
        flex_grow: f32,
        actions: Vec<String>,
        focused_action: Option<usize>,
    },
    Empty {
        description: String,
        icon_name: String,
        image: String,
    },
    Image {
        src: String,
        alt: String,
        fallback: String,
        width: f32,
        height: f32,
        radius: f32,
        preview: bool,
        preview_open: bool,
        fit: bool,
    },
    ImageGroup {
        images: Vec<String>,
        start_index: usize,
        current: usize,
        preview_open: bool,
    },
    Tag {
        text: String,
        color: TagColor,
        closable: bool,
        font_size: f32,
        custom_color: Option<Color>,
        checkable: bool,
        checked: bool,
        visible: bool,
        icon: String,
    },
    Timeline {
        items: Vec<TimelineItem>,
        pending: bool,
        reverse: bool,
    },
    Calendar {
        cell_size: f32,
        year_jump: bool,
        year: i32,
        month: usize,
        selected: Option<Date>,
        focused_day: usize,
    },
    Skeleton {
        shape: SkeletonShape,
        width: f32,
        height: f32,
    },
    FloatButton {
        icon: String,
        tooltip: String,
        badge_count: i32,
        size: f32,
        x: f32,
        y: f32,
        reserve_layout_space: bool,
    },
    FloatButtonGroup {
        button_count: usize,
        trigger: TriggerMode,
        expanded: bool,
    },
    Alert {
        message: String,
        description: String,
        type_: StatusLevel,
        closable: bool,
        show_icon: bool,
    },
    Message {
        placement: Placement,
        contents: Vec<String>,
    },
    Notification {
        placement: Placement,
        titles: Vec<String>,
        descriptions: Vec<String>,
    },
    ProgressBar {
        progress: f32,
        mode: ProgressMode,
        stroke_color: Option<Color>,
        track_color: Option<Color>,
        height: f32,
        width: f32,
        round: bool,
        progress_type: ProgressType,
    },
    Spin {
        size: SpinSize,
        color: Option<Color>,
        spinning: bool,
        tip: String,
        wrapper_mode: bool,
    },
    Tooltip {
        text: String,
        placement: TooltipPlacement,
        trigger: TriggerMode,
        bg_color: Option<Color>,
        text_color: Option<Color>,
        delay_ms: u32,
        timer_id: u32,
        arrow: bool,
    },
    Popover {
        title: String,
        content: String,
        placement: PopoverPlacement,
        trigger: PopoverTrigger,
        arrow: bool,
        visible: bool,
    },
    Popconfirm(SnapshotPopconfirm),
    Modal {
        title: String,
        open: bool,
        width: f32,
        height: f32,
        modal_size: ControlSize,
        closable: bool,
        mask_closable: bool,
        footer_visible: bool,
        centered: bool,
        overlay: bool,
    },
    Drawer {
        title: String,
        open: bool,
        width: f32,
        height: f32,
        drawer_size: ControlSize,
        placement: DrawerPlacement,
        closable: bool,
        mask_closable: bool,
        mask: bool,
        footer_visible: bool,
        extra: String,
    },
    Layout {
        bg_color: Option<Color>,
    },
    Header {
        height: f32,
        bg_color: Option<Color>,
    },
    Sider {
        width: f32,
        bg_color: Option<Color>,
        collapsible: bool,
        collapsed: bool,
        collapsed_width: f32,
    },
    Content {
        bg_color: Option<Color>,
    },
    Footer {
        height: f32,
        bg_color: Option<Color>,
    },
    Splitter {
        vertical: bool,
        panel_count: usize,
        min_sizes: Vec<f32>,
        handle_size: f32,
        ratios: Vec<f32>,
        active_handle: usize,
    },
    Affix {
        offset_top: f32,
        scroll_y: f32,
        affixed: bool,
    },
    BackTop {
        visibility_height: f32,
        visible: bool,
    },
    Breadcrumb {
        items: Vec<BreadcrumbItem>,
        separator: String,
    },
    Pagination {
        total: usize,
        page_size: usize,
        current: usize,
        show_size_changer: bool,
        show_total: bool,
        size: f32,
        page_size_options: Vec<usize>,
    },
    Anchor {
        items: Vec<AnchorItem>,
        active_index: usize,
        offset_top: f32,
        bg_color: Option<Color>,
    },
    Menu {
        items: Vec<MenuItem>,
        active_key: String,
        mode: MenuMode,
        item_h: f32,
    },
    Dropdown {
        label: String,
        items: Vec<String>,
        open: bool,
        selected_index: Option<usize>,
        highlighted_index: Option<usize>,
    },
    Tabs {
        tabs: Vec<Tab>,
        active_index: usize,
        active_key: Option<String>,
        position: TabPosition,
        tab_height: f32,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
    },
    Steps {
        steps: Vec<Step>,
        current: usize,
        direction: StepsDirection,
    },
    NavItem {
        label: String,
        key: String,
        icon: String,
        fixed_width: f32,
        fixed_height: f32,
        index: usize,
        compact: bool,
        active: bool,
    },
    Tree {
        nodes: Vec<SnapshotTreeNode>,
        selected_key: String,
        selected_keys: Vec<String>,
        expanded_keys: Vec<String>,
        multiple: bool,
    },
    List {
        header: String,
        footer: String,
        bordered: bool,
        list_size: ControlSize,
        items: Vec<String>,
        load_more_text: String,
    },
    Collapse {
        panels: Vec<SnapshotCollapsePanel>,
        accordion: bool,
        focused_header: usize,
    },
    Carousel {
        show_dots: bool,
        show_arrows: bool,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
        current: usize,
        slide_count: usize,
    },
    Select {
        options: Vec<String>,
        optgroups: Vec<OptGroup>,
        selected: usize,
        selected_multi: Vec<usize>,
        open: bool,
        disabled: bool,
        loading: bool,
        placeholder: String,
        multiple: bool,
        search: bool,
        search_query: String,
        custom_options: bool,
    },
    AutoComplete {
        placeholder: String,
        options: Vec<String>,
        value: String,
        open: bool,
    },
    TreeSelect {
        placeholder: String,
        nodes: Vec<SnapshotTreeNode>,
        value: String,
        value_key: String,
        open: bool,
    },
    Cascader {
        options: Vec<CascaderOption>,
        placeholder: String,
        selected_labels: Vec<String>,
        selected_values: Vec<String>,
        open: bool,
        loading_children: Vec<String>,
        searchable: bool,
        search_query: String,
        search_results: Vec<CascaderValue>,
    },
    ColorPicker {
        value: Color,
        preset_colors: Vec<Color>,
        open: bool,
    },
    DatePicker {
        placeholder: String,
        value: Option<String>,
        open: bool,
    },
    DateRangePicker {
        placeholder: String,
        start: Option<String>,
        end: Option<String>,
        open: bool,
    },
    TimePicker {
        placeholder: String,
        value: Option<String>,
        open: bool,
    },
    Mentions {
        placeholder: String,
        options: Vec<String>,
        value: String,
        suggesting: bool,
    },
    Segmented {
        options: Vec<String>,
        selected: usize,
        disabled: bool,
        disabled_options: Vec<bool>,
    },
    FormItem {
        label: String,
        name: String,
        required: bool,
        help: String,
        label_width: f32,
        layout: FormLayout,
    },
    Form {
        label_width: f32,
        gap: f32,
        layout: FormLayout,
    },
    Descriptions {
        title: String,
        items: Vec<DescriptionsItem>,
        bordered: bool,
        column: usize,
        label_width: f32,
        descriptions_size: ControlSize,
    },
    Result {
        result_type: ResultType,
        title: String,
        subtitle: String,
        extra_text: String,
    },
    // 表格 capability 关闭时同步收缩公开快照枚举。
    #[cfg(feature = "table")]
    // 启用后记录表格列、数据、布局与交互状态。
    Table {
        columns: Vec<SnapshotTableColumn>,
        column_groups: Vec<SnapshotTableColumnGroup>,
        rows: Vec<TableRow>,
        row_keys: Vec<String>,
        view_columns: Vec<usize>,
        row_h: f32,
        header_h: f32,
        expandable: bool,
        expand_height: f32,
        sortable: bool,
        selection: bool,
        bordered: bool,
        loading: bool,
        selected_row: Option<usize>,
        checked_rows: Vec<usize>,
        empty_text: String,
        current_page: Option<usize>,
        total: Option<usize>,
        page_size: usize,
        virtual_scroll: bool,
    },
    SelectableList {
        items: Vec<SelectableItem>,
        active_index: usize,
        header_button_text: String,
        footer_text: String,
        item_height: f32,
    },
    ScrollView {
        direction: ScrollDirection,
        fixed_width: Option<f32>,
        fixed_height: Option<f32>,
        flex_grow: f32,
        flex_shrink: f32,
        show_scrollbar: bool,
        scroll_x: f32,
        scroll_y: f32,
    },
    // 图表 capability 启用时才保留柱状图快照变体。
    #[cfg(feature = "charts")]
    // 启用后记录柱状图数据与布局配置。
    BarChart {
        data: Vec<BarData>,
        fixed_width: f32,
        fixed_height: f32,
        max_value: f32,
        show_value: bool,
        bar_radius: f32,
    },
    // 图表 capability 启用时才保留折线图快照变体。
    #[cfg(feature = "charts")]
    // 启用后记录折线图数据、布局与样式配置。
    LineChart {
        data: Vec<LineData>,
        fixed_width: f32,
        fixed_height: f32,
        line_color: Option<Color>,
        max_value: f32,
        auto_min: bool,
        show_grid: bool,
        show_dots: bool,
        line_width: f32,
        dot_radius: f32,
    },
    // 图表 capability 启用时才保留饼图快照变体。
    #[cfg(feature = "charts")]
    // 启用后记录饼图数据与环形布局配置。
    PieChart {
        data: Vec<PieData>,
        fixed_size: f32,
        hole_radius: f32,
    },
    // 图表 capability 启用时才保留高级图表快照变体。
    #[cfg(feature = "charts")]
    // 启用后记录高级图表的标题与类型摘要。
    ChartPlaceholder {
        title: String,
        subtitle: String,
        kind_name: &'static str,
    },
    // 关闭二维码 capability 时同步收缩公开快照枚举。
    #[cfg(feature = "qrcode")]
    // 启用后保留二维码编码与矩阵状态字段。
    QRCode {
        value: String,
        size: f32,
        error_level: u8,
        module_count: usize,
        encoding_error: Option<String>,
    },
    // 关闭富文本 capability 时同步收缩公开快照枚举。
    #[cfg(feature = "rich-text")]
    // 启用后保留富文本内容、样式与焦点状态字段。
    RichText {
        segments: Vec<RichTextSegment>,
        default_font_size: f32,
        default_font_size_unit: Option<PhysicalUnit>,
        default_color: Color,
        focused_link: Option<usize>,
    },
    ThemeToggle {
        dark: bool,
    },
    Transfer {
        source: Vec<SnapshotTransferItem>,
        target: Vec<SnapshotTransferItem>,
    },
    Upload {
        accept: String,
        multiple: bool,
        drag: bool,
        max_count: usize,
        max_size: Option<u64>,
        show_upload_list: bool,
        preview_image: bool,
        manual: bool,
        files: Vec<UploadFile>,
    },
    Watermark {
        text: String,
        color: Color,
        font_size: f32,
        opacity: f32,
        rotate: f32,
        gap_x: f32,
        gap_y: f32,
        x_offset: f32,
        y_offset: f32,
    },
    Container {
        style: Style,
    },
    Grid {
        style: Style,
        breakpoints: Option<Breakpoints>,
        cols: Vec<Col>,
    },
}
